AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation to deploy the collaboration environment

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucketname-{AWS::AccountId}-{AWS::Region}
