AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyBucketName:
    Type: String
    Description: The name of the S3 bucket to create
    Default: my-bucket-name

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MyBucketName

