AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation to deploy the arpa-h collaboration installer
Parameters:
  ConnectionArn:
    Type: String
    Description: The code star connection arn
    Default: "arn:aws:codestar-connections:us-east-1:905418411195:connection/4f63b4d1-3de5-4d85-90a6-a465347969a1"
  PrincipalArn:
    Type: String
    Description: The principal arn pattern to associate with the portfolios
    Default: "arn:aws:iam:::role/*"

Resources:
  ArpahPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: "Arpa-h Portfolio"
      ProviderName: "Arpa-h"
      Description: "Arpa-h Portfolio"
      Tags:
        - Key: "Name"
          Value: "Arpa-h Portfolio"
        - Key: "Version"
          Value: "1.0"

  PortfolioPrincipalAssociation:  
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      AcceptLanguage: "en"
      PortfolioId: !Ref ArpahPortfolio
      PrincipalARN: !Ref PrincipalArn
      PrincipalType: "IAM_PATTERN"
  
  CollaborationProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: "CollaborationProduct"
      Owner: "arpah"
      Description: "Arpa-h Collaboration Solution"
      SourceConnection:
          ConnectionParameters: 
              CodeStar: 
                  ArtifactPath: collaboration.yaml
                  Branch: arpaExample
                  ConnectionArn: !Ref ConnectionArn
                  Repository: jasoaws/NCI-Sarek-Workflow
          Type: CODESTAR
      Tags:
        - Key: "Name"
          Value: "FinOpsProduct"
        - Key: "Version"
          Value: "1.0"

  CollaborationProductPortfolioAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      AcceptLanguage: "en"
      PortfolioId: !Ref ArpahPortfolio
      ProductId: !Ref CollaborationProduct
    
  CollaborationProvisionedProduct:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    DependsOn: CollaborationProductPortfolioAssociation
    Properties:
      ProductName: !GetAtt CollaborationProduct.ProductName
      ProvisioningArtifactId: !GetAtt CollaborationProduct.ProvisioningArtifactIds
      ProvisioningParameters:
        - Key: "pConnectionArn"
          Value: !Ref ConnectionArn
        - Key: "pPortfolioId"
          Value: !Ref ArpahPortfolio