AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation to deploy the collaboration environment

Parameters:
  ConnectionArn:
    Type: String
    Description: The code star connection arn
    Default: "arn:aws:codestar-connections:us-east-1:905418411195:connection/4f63b4d1-3de5-4d85-90a6-a465347969a1"
  PrincipalArn:
    Type: String
    Description: The principal arn pattern to associate with the portfolios
    Default: "arn:aws:iam:::role/*"

Resources:
  ArpahPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: "Arpa-h Portfolio"
      ProviderName: "Arpa-h"
      Description: "Arpa-h Portfolio"
      Tags:
        - Key: "Name"
          Value: "Arpa-h Portfolio"
        - Key: "Version"
          Value: "1.0"
  PortfolioPrincipalAssociation:  
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      AcceptLanguage: "en"
      PortfolioId: !Ref ArpahPortfolio
      PrincipalARN: !Ref PrincipalArn
      PrincipalType: "IAM_PATTERN"

  FinOpsProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: "FinOpsProduct"
      Owner: "arpah"
      Description: "Arpa-h FinOps Solution"
      SourceConnection:
          ConnectionParameters: 
              CodeStar: 
                  ArtifactPath: finops_cfn.yaml
                  Branch: main
                  ConnectionArn: !Ref ConnectionArn
                  Repository: jasoaws/sc-example
          Type: CODESTAR
      Tags:
        - Key: "Name"
          Value: "FinOpsProduct"
        - Key: "Version"
          Value: "1.0"

  WorkflowProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: "WorkflowProduct"
      Owner: "arpah"
      Description: "Arpa-h Workflow Solution"
      SourceConnection:
          ConnectionParameters: 
              CodeStar: 
                  ArtifactPath: workflow_cfn.yaml
                  Branch: main
                  ConnectionArn: !Ref ConnectionArn
                  Repository: jasoaws/sc-example
          Type: CODESTAR
      Tags:
        - Key: "Name"
          Value: "WorkflowProduct"
        - Key: "Version"
          Value: "1.0"

  WorkflowProductPortfolioAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      AcceptLanguage: "en"
      PortfolioId: !Ref ArpahPortfolio
      ProductId: !Ref WorkflowProduct
  FinopsProductPortfolioAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      AcceptLanguage: "en"
      PortfolioId: !Ref ArpahPortfolio
      ProductId: !Ref FinOpsProduct
  
  FinOpsProvisionedProduct:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    DependsOn: FinopsProductPortfolioAssociation
    Properties:
      ProductName: !GetAtt FinOpsProduct.ProductName
      ProvisioningArtifactId: !GetAtt FinOpsProduct.ProvisioningArtifactIds